UsersSignup:
  post:
    tags:
      - users
    summary: 회원 가입 API
    requestBody:
      $ref: "./components/requestBodies/users.yaml#/UserSignUpRequest"
    responses:
      201:
        $ref: "./components/responses/users.yaml#/UserSignUpSuccess"
      400:
        $ref: "./components/responses/users.yaml#/UserSignUpBadRequest"
      409:
        $ref: "./components/responses/users.yaml#/UserAlreadyExists"
      500:
        $ref: "./components/responses/users.yaml#/UserSignUpServerError"

CreateStore:
  post:
    tags:
      - stores
    summary: 가게 추가 API
    requestBody:
      $ref: "./components/requestBodies/store.yaml#/CreateStoreRequest"
    responses:
      201:
        $ref: "./components/responses/store.yaml#/CreateStoreSuccess"
      400:
        $ref: "./components/responses/store.yaml#/CreateStoreBadRequest"
      500:
        $ref: "./components/responses/store.yaml#/CreateStoreServerError"

AddReview:
  post:
    tags:
      - stores
    summary: 리뷰 추가 API
    requestBody:
      $ref: "./components/requestBodies/reviews.yaml#/AddReviewRequest"
    responses:
      201:
        $ref: "./components/responses/reviews.yaml#/AddReviewSuccess"
      400:
        $ref: "./components/responses/reviews.yaml#/AddReviewBadRequest"
      404:
        $ref: "./components/responses/reviews.yaml#/StoreNotFound"
      500:
        $ref: "./components/responses/reviews.yaml#/AddReviewServerError"

ListUserReviews:
  get:
    tags:
      - users
    summary: 리뷰 목록 조회 API
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: number
        description: 리뷰를 조회할 userId
      - in: query
        name: cursor
        required: false
        schema:
          type: number
          example: 10
        description: 페이지네이션 커서
    responses:
      200:
        $ref: "./components/responses/reviews.yaml#/ListReviewsSuccess"
      404:
        $ref: "./components/responses/reviews.yaml#/UserReviewNotFound"

AddMission:
  post:
    tags:
      - missions
    summary: 미션 추가 API
    parameters:
      - in: path
        name: storeId
        required: true
        schema:
          type: number
        description: 미션을 추가할 storeId
    requestBody:
      $ref: "./components/requestBodies/missions.yaml#/AddMissionRequest"
    responses:
      201:
        $ref: "./components/responses/missions.yaml#/AddMissionSuccess"
      400:
        $ref: "./components/responses/missions.yaml#/AddMissionBadRequest"
      404:
        $ref: "./components/responses/missions.yaml#/MissionStoreNotFound"
      500:
        $ref: "./components/responses/missions.yaml#/AddMissionServerError"


StoreMissions:
  get:
    tags:
      - missions
    summary: 특정 가게에서의 미션 목록 조회 API
    parameters:
      - in: path
        name: storeId
        required: true
        schema:
          type: number
      - in: query
        name: cursor
        required: false
        schema:
          type: number
          example: 10
        description: 페이지네이션 커서
    responses:
      200:
        $ref: "./components/responses/missions.yaml#/MissionListSuccess"
      404:
        $ref: "./components/responses/missions.yaml#/MissionNotFound"

UserMissionCreate:
  post:
    tags:
      - usermissions
    summary: 사용자 미션 등록 API
    parameters:
      - in: path
        name: storeId
        required: true
        schema:
          type: number
        description: 가게 ID
      - in: path
        name: missionId
        required: true
        schema:
          type: number
        description: 미션 ID
    requestBody:
      $ref: "./components/requestBodies/usermissions.yaml#/UserMissionCreateRequest"
    responses:
      201:
        $ref: "./components/responses/usermissions.yaml#/UserMissionCreateSuccess"
      404:
        $ref: "./components/responses/usermissions.yaml#/MissionNotFound"
      400:
        $ref: "./components/responses/usermissions.yaml#/UserMissionBadRequest"
      500:
        $ref: "./components/responses/usermissions.yaml#/UserMissionServerError"


UserMissionList:
  get:
    tags:
      - usermissions
    summary: 진행 중인 사용자 미션 목록 조회 API
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: number
        description: 사용자 ID
      - in: query
        name: cursor
        required: false
        schema:
          type: number
          example: 10
        description: 페이지네이션 커서
    responses:
      200:
        $ref: "./components/responses/usermissions.yaml#/UserMissionListSuccess"
      404:
        $ref: "./components/responses/usermissions.yaml#/UserMissionListNotFound"


UserMissionComplete:
  patch:
    tags:
      - usermissions
    summary: 사용자 미션 완료 처리 API
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: number
      - in: path
        name: userMissionId
        required: true
        schema:
          type: number
        description: 유저 미션 ID
    responses:
      200:
        $ref: "./components/responses/usermissions.yaml#/UserMissionCompleteSuccess"
      404:
        $ref: "./components/responses/usermissions.yaml#/MissionNotFound"
      400:
        $ref: "./components/responses/usermissions.yaml#/UserMissionBadRequest"
      500:
        $ref: "./components/responses/usermissions.yaml#/UserMissionServerError"
